spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moneybook
    username: mahadi
    password: mahadi
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update