spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/Draft
    username: mahadi
    password: mahadi
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect