spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/draft
    username: root
    password: mahadi
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true